# [build-system]
# requires = ["setuptools"]
# build-backend = "setuptools.build_meta"

[project]
name = "exploit_shell_umbraco"
version = "0.0.1"
dependencies = []
authors = [
    {name = "Maurice Lambert", email = "mauricelambert434@gmail.com"},
]
maintainers = [
    {name = "Maurice Lambert", email = "mauricelambert434@gmail.com"},
]
description = 'This module implements a shell to exploit a RCE in umbraco CMS.'
readme = {file = "README.md", content-type = "text/markdown"}
# url = "https://github.com/mauricelambert/exploit_shell_umbraco"
# download-url = "https://mauricelambert.github.io/info/python/security/exploit_shell_umbraco.pyz"
classifiers = [
    "Topic :: System",
    "Topic :: Security",
    "Environment :: Console",
    "Topic :: System :: Shells",
    'Operating System :: POSIX',
    "Natural Language :: English",
    "Topic :: System :: Networking",
    "Topic :: Internet :: WWW/HTTP",
    "Programming Language :: Python",
    "Intended Audience :: Developers",
    "Topic :: System :: System Shells",
    'Operating System :: MacOS :: MacOS X',
    "Programming Language :: Python :: 3.8",
    'Operating System :: Microsoft :: Windows',
    "Topic :: System :: Systems Administration",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]
keywords = ['exploit', 'umbraco', 'rce', 'shell', 'HackTheBox', 'python3', 'web']
license = {text = "GPL-3.0 License"}
requires-python = ">=3.8"

[project.scripts]
exploit_shell_umbraco = "exploit_shell_umbraco:main"

[project.urls]
"Github" = "https://github.com/mauricelambert/exploit_shell_umbraco"

[tool.setuptools]
include-package-data = true
platforms = ['Windows', 'Linux', "MacOS"]
py-modules = ['exploit_shell_umbraco', 'exploit_umbraco']
packages = []
script-files = []

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}
